@extends('layout.master')
@section('content')

    <!-- Main Content -->
    <main class="container mx-auto px-6 py-12 md:py-20">
        <div class="max-w-4xl mx-auto">
            <div class="text-center mb-12">
                <h1 class="text-4xl md:text-5xl font-extrabold text-gray-900 leading-tight">
                    Schedule Your Consultation
                </h1>
                <p class="mt-4 max-w-2xl mx-auto text-lg text-gray-600">
                    Let's connect. Choose a service and select a time that works best for you.
                </p>
            </div>

            <div class="bg-white p-8 rounded-xl border border-gray-200 shadow-lg">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                    
                    <!-- Left Column: Service Selection -->
                    <div class="md:col-span-1 border-b md:border-b-0 md:border-r border-gray-200 pb-8 md:pb-0 md:pr-8">
                        <h2 class="text-xl font-bold text-gray-900">1. Select a Service</h2>
                        <div class="mt-6 space-y-4">
                            <div id="service-free" class="service-option p-4 border-2 border-blue-500 bg-blue-50 rounded-lg cursor-pointer service-active">
                                <p class="font-semibold text-blue-800">Free Discovery Call</p>
                                <p class="text-sm text-blue-700 mt-1">30 minutes</p>
                            </div>
                            <div id="service-paid" class="service-option p-4 border border-gray-300 rounded-lg cursor-pointer hover:border-blue-500">
                                <p class="font-semibold text-gray-800">Styling Consultation</p>
                                <p class="text-sm text-gray-600 mt-1">1 hour - ₦25,000</p>
                            </div>
                        </div>
                    </div>

                    <!-- Right Column: Calendar & Time -->
                    <div class="md:col-span-2">
                        <h2 class="text-xl font-bold text-gray-900">2. Choose a Date & Time</h2>
                        
                        <!-- Interactive Calendar -->
                        <div class="mt-6">
                            <div class="flex justify-between items-center">
                                <button id="prev-month-btn" class="p-2 rounded-full hover:bg-gray-100"><i data-lucide="chevron-left" class="w-5 h-5 text-gray-600"></i></button>
                                <h3 id="month-year-title" class="text-lg font-semibold text-gray-900">July 2025</h3>
                                <button id="next-month-btn" class="p-2 rounded-full hover:bg-gray-100"><i data-lucide="chevron-right" class="w-5 h-5 text-gray-600"></i></button>
                            </div>
                            <div class="calendar-grid text-center text-sm mt-4">
                                <div class="font-semibold text-gray-500 py-2">Sun</div><div class="font-semibold text-gray-500 py-2">Mon</div><div class="font-semibold text-gray-500 py-2">Tue</div><div class="font-semibold text-gray-500 py-2">Wed</div><div class="font-semibold text-gray-500 py-2">Thu</div><div class="font-semibold text-gray-500 py-2">Fri</div><div class="font-semibold text-gray-500 py-2">Sat</div>
                                <!-- Calendar days will be generated by JS -->
                            </div>
                        </div>
                        
                        <!-- Time Slot Picker -->
                        <div id="time-slot-section" class="mt-6">
                            <h3 class="font-semibold text-gray-800">Available Times for <span id="selected-date-text" class="text-blue-600">July 29, 2025</span></h3>
                            <div id="time-slots" class="mt-4 grid grid-cols-3 sm:grid-cols-4 gap-3">
                                <!-- Time slots will be generated by JS -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Final Step: Details Form -->
                <div class="mt-8 pt-8 border-t border-gray-200">
                    <h2 class="text-xl font-bold text-gray-900">3. Enter Your Details</h2>
                    
                   

                    <form class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label for="name" class="block text-sm font-medium text-gray-700">Full Name</label>
                            <input type="text" id="name" class="mt-1 block w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
                        </div>
                        <div>
                            <label for="email" class="block text-sm font-medium text-gray-700">Email Address</label>
                            <input type="email" id="email" class="mt-1 block w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
                        </div>
                        <div class="md:col-span-2">
                             <label for="details" class="block text-sm font-medium text-gray-700">Please provide a brief description of your needs</label>
                             <textarea id="details" rows="4" class="mt-1 block w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm"></textarea>
                        </div>
                    </form>
                </div>
                
                <!-- Confirmation Button -->
                <div class="mt-8 flex justify-end">
                    <button class="bg-blue-600 text-white hover:bg-blue-700 font-semibold py-3 px-8 rounded-lg text-lg transition-colors shadow-lg hover:shadow-xl">
                        Confirm Booking
                    </button>
                </div>
            </div>
        </div>
    </main>
@endsection
