@extends('layout.master')
@section('content')

    <!-- Hero Section with Image Carousel -->
        <section id="home" class="relative h-[90vh] md:h-[85vh] w-full slider-container">
        <div class="hero-slider-track h-full">
            <!-- Slide 1 -->
            <div class="hero-slide h-full">
                <img src="https://images.unsplash.com/photo-1709884735626-63e92727d8b6?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Fashion model 1">
            </div>
            <!-- Slide 2 -->
            <div class="hero-slide h-full">
                <img src="https://plus.unsplash.com/premium_photo-1683140721927-aaed410fae29?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Fashion model 2">
            </div>
            <!-- Slide 3 -->
            <div class="hero-slide h-full">
                <img src="https://images.unsplash.com/photo-1645120578522-16c6debcc1c0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Fashion model 3">
            </div>
            <!-- Slide 4 -->
            <div class="hero-slide h-full">
                <img src="https://plus.unsplash.com/premium_photo-1683140721927-aaed410fae29?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Fashion model 4">
            </div>
        </div>

        <!-- Hero Content Overlay -->
        <div class="absolute inset-0 bg-black/50"></div>
        <div class="absolute inset-0 container mx-auto px-6 flex flex-col justify-center items-center text-white">
            <div class="w-full max-w-3xl text-center">
                <span class="text-orange-400 font-semibold">New Collection 2025</span>
                <h1 class="text-4xl md:text-6xl font-extrabold leading-tight mt-4">Modern Styles, <br>Timeless Roots.</h1>
                <p class="mt-6 max-w-lg mx-auto text-lg text-gray-200">Discover authentic, handcrafted Nigerian fashion that celebrates culture and empowers artisans.</p>
                <!-- <a href="#shop" class="mt-8 inline-block bg-orange-500 text-white hover:bg-orange-600 font-semibold py-3 px-8 rounded-lg text-lg transition-colors shadow-lg hover:shadow-xl">
                    Shop Bestsellers
                </a> -->

                <div class="mt-8 flex flex-col sm:flex-row justify-center gap-4">
                    <a href="#products" class="bg-white text-purple-700 font-semibold px-6 py-3 rounded-full hover:bg-purple-100 transition">Explore Products</a>
                    <a href="#services" class="bg-purple-600 hover:bg-purple-700 text-white font-semibold px-6 py-3 rounded-full transition">Book a Service</a>
                </div>
            </div>
        </div>

        <!-- Carousel Navigation -->
        <div class="absolute bottom-8 right-8 flex items-center space-x-4">
            <button id="heroPrevBtn" class="bg-white/20 text-white p-3 rounded-full hover:bg-white/40 transition-colors backdrop-blur-sm">
                <i data-lucide="chevron-left" class="w-6 h-6"></i>
            </button>
            <button id="heroNextBtn" class="bg-white/20 text-white p-3 rounded-full hover:bg-white/40 transition-colors backdrop-blur-sm">
                <i data-lucide="chevron-right" class="w-6 h-6"></i>
            </button>
        </div>

        <!-- Carousel Pagination Dots -->
        <div id="heroPagination" class="absolute bottom-8 left-1/2 -translate-x-1/2 flex space-x-2">
            <!-- Dots will be generated by JS -->
        </div>
    </section>

        <!-- Product Categories Section -->
    <section id="categories" class="py-20 bg-gray-50">
        <div class="container mx-auto px-6">
            <div class="bg-white p-8 md:p-12 rounded-2xl grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                <!-- Left Column: Categories List -->
                <div>
                    <div class="flex items-center gap-2">
                        <span class="text-yellow-500"><i data-lucide="star" class="w-5 h-5 fill-current"></i></span>
                        <span class="text-yellow-500"><i data-lucide="star" class="w-5 h-5 fill-current"></i></span>
                        <span class="text-yellow-500"><i data-lucide="star" class="w-5 h-5 fill-current"></i></span>
                        <span class="text-yellow-500"><i data-lucide="star" class="w-5 h-5 fill-current"></i></span>
                        <span class="text-yellow-500"><i data-lucide="star" class="w-5 h-5 fill-current"></i></span>
                        <span class="ml-2 text-sm text-gray-600">Rated 5/5 by our customers</span>
                    </div>
                    <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mt-4">Shop by Category</h2>
                    <p class="mt-3 text-lg text-gray-600">Find the perfect piece for any occasion.</p>
                    <div class="mt-8 space-y-4">
                        <a href="#" class="flex items-center p-3 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
                            <i data-lucide="shirt" class="w-6 h-6 text-orange-500 mr-4"></i>
                            <span class="font-semibold text-gray-800">Gowns & Dresses</span>
                        </a>
                        <a href="#" class="flex items-center p-3 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
                            <i data-lucide="briefcase" class="w-6 h-6 text-orange-500 mr-4"></i>
                            <span class="font-semibold text-gray-800">Bags & Purses</span>
                        </a>
                            <a href="#" class="flex items-center p-3 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
                            <i data-lucide="gem" class="w-6 h-6 text-orange-500 mr-4"></i>
                            <span class="font-semibold text-gray-800">Jewelry & Accessories</span>
                        </a>
                        <a href="#" class="flex items-center p-3 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
                            <i data-lucide="layers" class="w-6 h-6 text-orange-500 mr-4"></i>
                            <span class="font-semibold text-gray-800">Fabric & Textiles</span>
                        </a>
                    </div>
                </div>
                <!-- Right Column: Image -->
                <div class="w-full h-80 md:h-full rounded-2xl overflow-hidden">
                    <img src="https://plus.unsplash.com/premium_photo-1683140721927-aaed410fae29?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Category showcase" class="w-full h-full object-cover">
                </div>
            </div>
        </div>
    </section>
    <!-- Featured Products Section -->
    <section id="shop" class="py-20 bg-gray-50">
        <div class="container mx-auto px-6">
            <div class="text-center mb-12">
                <h2 class="text-3xl md:text-4xl font-bold text-gray-900">Our Bestsellers</h2>
                <p class="mt-3 text-lg text-gray-600">The pieces our customers can't get enough of.</p>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
                <!-- Product Cards -->
                    <a href="product_detail.html">
                    <div class="bg-white rounded-xl overflow-hidden group">
                        <img src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?q=80&w=1147&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Product" class="w-full h-80 object-cover group-hover:opacity-80 transition-opacity duration-300">
                        <div class="p-6">
                            <h3 class="text-lg font-semibold text-gray-800">Luxury Beaded Gown</h3>
                            <p class="mt-2 text-xl font-bold text-gray-900">₦75,000</p>
                            <button class="mt-4 w-full bg-orange-500 text-white font-semibold py-3 px-4 rounded-lg flex items-center justify-center transition-colors shadow-sm hover:bg-orange-600">
                                <i data-lucide="shopping-cart" class="w-5 h-5 mr-2"></i> Order on WhatsApp
                            </button>
                        </div>
                    </div>
                    </a>

                <div class="bg-white rounded-xl overflow-hidden group">
                    <img src="https://placehold.co/400x400/fef9c3/b45309?text=Bag" alt="Product" class="w-full h-80 object-cover group-hover:opacity-80 transition-opacity duration-300">
                    <div class="p-6">
                        <h3 class="text-lg font-semibold text-gray-800">Leather Handbag</h3>
                        <p class="mt-2 text-xl font-bold text-gray-900">₦25,000</p>
                        <button class="mt-4 w-full bg-orange-500 text-white font-semibold py-3 px-4 rounded-lg flex items-center justify-center transition-colors shadow-sm hover:bg-orange-600">
                            <i data-lucide="shopping-cart" class="w-5 h-5 mr-2"></i> Order on WhatsApp
                        </button>
                    </div>
                </div>
                <div class="bg-white rounded-xl overflow-hidden group">
                    <img src="https://placehold.co/400x400/dcfce7/166534?text=Fabric" alt="Product" class="w-full h-80 object-cover group-hover:opacity-80 transition-opacity duration-300">
                    <div class="p-6">
                        <h3 class="text-lg font-semibold text-gray-800">Ankara Print Fabric</h3>
                        <p class="mt-2 text-xl font-bold text-gray-900">₦12,000</p>
                        <button class="mt-4 w-full bg-orange-500 text-white font-semibold py-3 px-4 rounded-lg flex items-center justify-center transition-colors shadow-sm hover:bg-orange-600">
                            <i data-lucide="shopping-cart" class="w-5 h-5 mr-2"></i> Order on WhatsApp
                        </button>
                    </div>
                </div>
                <div class="bg-white rounded-xl overflow-hidden group">
                    <img src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?q=80&w=1147&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Product" class="w-full h-80 object-cover group-hover:opacity-80 transition-opacity duration-300">
                    <div class="p-6">
                        <h3 class="text-lg font-semibold text-gray-800">Aso-Oke Head Tie</h3>
                        <p class="mt-2 text-xl font-bold text-gray-900">₦15,000</p>
                        <button class="mt-4 w-full bg-orange-500 text-white font-semibold py-3 px-4 rounded-lg flex items-center justify-center transition-colors shadow-sm hover:bg-orange-600">
                            <i data-lucide="shopping-cart" class="w-5 h-5 mr-2"></i> Order on WhatsApp
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Main About Block -->
    <section id="categories" class="py-20 bg-gray-50">
        <div class="container mx-auto px-6">
            <div class="bg-white p-8 md:p-12 rounded-2xl grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                <!-- Left Column: Categories List -->
                <div>
                    <div class="flex items-center gap-2">
                        <span class="text-sm font-semibold text-blue-600 bg-blue-100 px-3 py-1 rounded-full">ABOUT US</span>
                    </div>
                    <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mt-4">Empowering the Next Generation of Nigerian Entrepreneurs</h2>
                    <p class="mt-3 text-lg text-gray-600"> Ervop was born from a simple observation: millions of talented Nigerian entrepreneurs are running their businesses on a chaotic mix of social media DMs, notebooks, and personal bank accounts. We built this platform to provide the structure, tools, and professional image they need to turn their hustle into a scalable business.</p>
                    <div class="mt-8 space-y-4">
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-8 items-center">
                            <div class="md:col-span-3 ">
                                <div class="flex space-x-8">
                                    <div>
                                        <p class="text-4xl font-bold text-blue-600">10+</p>
                                        <p class="text-gray-500 mt-1">Years of Experience</p>
                                    </div>
                                    <div>
                                        <p class="text-4xl font-bold text-blue-600">1,000+</p>
                                        <p class="text-gray-500 mt-1">Businesses Empowered</p>
                                    </div>

                                </div>
                                <!-- NEW: CTA Button Added Here -->
                                <div class="mt-8">
                                    <a href="#" class="bg-blue-600 text-white hover:bg-blue-700 font-semibold py-3 px-6 rounded-lg transition-colors shadow-sm">
                                        Explore More
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Right Column: Image -->
                <div class="w-full h-80 md:h-full rounded-2xl overflow-hidden">
                    <img src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?q=80&w=1147&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Category showcase" class="w-full h-full object-cover">
                </div>
            </div>
        </div>
    </section>


    <!-- Services Section -->
    <section id="services" class="py-20 bg-gray-50">
        <div class="container mx-auto px-6">
            <div class="text-center mb-12">
                <h2 class="text-3xl md:text-4xl font-bold text-gray-900">Professional Services</h2>
                <p class="mt-3 text-lg text-gray-600">Expert guidance to bring your vision to life.</p>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
                <!-- Service Card 1 -->
                <div class="bg-white p-8 rounded-xl border border-gray-200">
                    <i data-lucide="palette" class="w-10 h-10 text-blue-600"></i>
                    <h3 class="mt-5 text-xl font-bold text-gray-900">Styling Consultation</h3>
                    <p class="mt-3 text-gray-600">A one-on-one session to define your personal style and curate the perfect look for any event.</p>
                </div>
                <!-- Service Card 2 -->
                <div class="bg-white p-8 rounded-xl border border-gray-200">
                    <i data-lucide="scissors" class="w-10 h-10 text-blue-600"></i>
                    <h3 class="mt-5 text-xl font-bold text-gray-900">Custom Design</h3>
                    <p class="mt-3 text-gray-600">Collaborate with me to create a unique, bespoke outfit tailored perfectly to you.</p>
                </div>
                <!-- Service Card 3 -->
                <div class="bg-white p-8 rounded-xl border border-gray-200">
                    <i data-lucide="users" class="w-10 h-10 text-blue-600"></i>
                    <h3 class="mt-5 text-xl font-bold text-gray-900">Group Workshops</h3>
                    <p class="mt-3 text-gray-600">Join a fun, interactive workshop to learn the art of textile design and creation.</p>
                </div>
            </div>
        </div>
    </section>

        <!-- Why Choose Us Section -->
    <section class="w-full">
        <div class="container mx-auto px-6">
            <div class="text-center mb-12">
                <span class="text-sm font-semibold text-blue-600 bg-blue-100 px-3 py-1 rounded-full">WHY CHOOSE US</span>
                <h2 class="text-3xl md:text-5xl font-extrabold text-gray-900 mt-4">Why Ervop is The Right Choice for You</h2>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">

                <!-- Card 1: All-in-One Platform -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-gray-200">
                    <div class="bg-blue-100 text-blue-600 w-12 h-12 rounded-lg flex items-center justify-center">
                        <i data-lucide="layout-grid" class="w-6 h-6"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-900 mt-5">All-in-One Platform</h3>
                    <p class="mt-2 text-gray-600">Manage your website, sales, bookings, and clients from one single, simple dashboard. No more juggling multiple apps.</p>
                </div>

                <!-- Card 2: Built for Nigeria -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-gray-200">
                    <div class="bg-green-100 text-green-600 w-12 h-12 rounded-lg flex items-center justify-center">
                        <i data-lucide="flag" class="w-6 h-6"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-900 mt-5">Built for Nigeria</h3>
                    <p class="mt-2 text-gray-600">With features like WhatsApp orders and CAC verification, Ervop is designed for the way you actually do business.</p>
                </div>

                <!-- Card 3: Flexible Learning Schedules (The Large Card) -->
                <div class="bg-blue-600 text-white p-8 rounded-2xl shadow-lg md:row-span-2 flex flex-col">
                    <div class="bg-white/20 text-white w-12 h-12 rounded-lg flex items-center justify-center">
                        <i data-lucide="rocket" class="w-6 h-6"></i>
                    </div>
                    <h3 class="text-2xl font-bold mt-5">Grow Faster</h3>
                    <p class="mt-2 text-blue-100 flex-grow">
                        At Ervop, we understand the importance of looking professional and operating efficiently. Our tools are designed to save you time and help you build a brand that customers trust, allowing you to focus on what you do best.
                    </p>
                    <button class="mt-6 bg-white text-blue-700 font-semibold py-3 px-6 rounded-lg w-full flex items-center justify-center hover:bg-blue-50 transition-colors">
                        <span>Start for Free</span>
                        <i data-lucide="arrow-right" class="w-4 h-4 ml-2"></i>
                    </button>
                </div>

                <!-- Card 4: For Sellers & Professionals -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-gray-200">
                    <div class="bg-blue-100 text-blue-600 w-12 h-12 rounded-lg flex items-center justify-center">
                        <i data-lucide="layout-grid" class="w-6 h-6"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-900 mt-5">All-in-One Platform</h3>
                    <p class="mt-2 text-gray-600">Manage your website, sales, bookings, and clients from one single, simple dashboard. No more juggling multiple apps.</p>
                </div>

                <!-- Card 2: Built for Nigeria -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-gray-200">
                    <div class="bg-green-100 text-green-600 w-12 h-12 rounded-lg flex items-center justify-center">
                        <i data-lucide="flag" class="w-6 h-6"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-900 mt-5">Built for Nigeria</h3>
                    <p class="mt-2 text-gray-600">With features like WhatsApp orders and CAC verification, Ervop is designed for the way you actually do business.</p>
                </div>

            </div>
        </div>
    </section>

    <!-- Booking Section -->
    <section id="booking" class="py-20">
        <div class="container mx-auto px-6 text-center">
            <h2 class="text-3xl font-bold text-gray-900">Let's Create Something Beautiful Together</h2>
            <p class="mt-4 max-w-xl mx-auto text-lg text-gray-600">A 30-minute discovery call is the first step to understanding your needs and exploring how I can help. It's completely free.</p>
            <div class="mt-10">
                <a href="#" class="bg-blue-600 text-white hover:bg-blue-700 font-semibold py-3 px-8 rounded-lg text-lg transition-colors shadow-lg hover:shadow-xl">
                    Book Your Free Call Now
                </a>
            </div>
        </div>
    </section>


    <!-- Testimonials Section -->
    <section class="py-20 bg-gray-50">
        <div class="container mx-auto px-6">
            <h2 class="text-center text-3xl font-bold text-gray-900">What Our Customers Say</h2>
            <div class="relative max-w-3xl mx-auto mt-12 slider-container">
                <div class="slider-track">
                    <!-- Slides -->
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"The quality is exceptional! A true Nigerian brand to be proud of!"</p><p class="mt-6 font-bold text-lg">- Chioma N.</p></div>
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"My leather bag is my new favorite accessory. Stylish and durable."</p><p class="mt-6 font-bold text-lg">- Tunde A.</p></div>
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"Amazing customer service. They helped me choose the perfect fabric."</p><p class="mt-6 font-bold text-lg">- Funke O.</p></div>
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"Finally, a brand that represents our culture with such elegance."</p><p class="mt-6 font-bold text-lg">- Emeka I.</p></div>
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"The Aso-Oke is even more beautiful in person. Top-notch craftsmanship."</p><p class="mt-6 font-bold text-lg">- Aisha B.</p></div>
                    <div class="slide p-4 text-center"><p class="text-xl text-gray-700 italic">"Fast delivery and beautiful packaging. They care about every detail."</p><p class="mt-6 font-bold text-lg">- David A.</p></div>
                </div>
                <button id="prevBtn" class="absolute top-1/2 left-0 md:-left-12 transform -translate-y-1/2 bg-white p-2 rounded-full shadow-md hover:bg-gray-100"><i data-lucide="chevron-left" class="w-6 h-6 text-gray-600"></i></button>
                <button id="nextBtn" class="absolute top-1/2 right-0 md:-right-12 transform -translate-y-1/2 bg-white p-2 rounded-full shadow-md hover:bg-gray-100"><i data-lucide="chevron-right" class="w-6 h-6 text-gray-600"></i></button>
            </div>
        </div>
    </section>
@endsection
